apiVersion: v1
kind: Pod
metadata:
  name: ui
  labels:
    app: ui
spec:
  containers:
  - name: ui
    image: ##DOCKER_PREFIX##/ui:latest
    ports:
      - containerPort: 80
        name: http-port
  imagePullSecrets:
  - name: ocirsecret        
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
  - name: http-service-port
    protocol: TCP
    port: 80
    targetPort: http-port
---    