-- DROP DATABASE db1;
show databases;
create database db1;
use db1;

-- DROP TABLE DEPT;
CREATE TABLE DEPT
       (DEPTNO INTEGER PRIMARY KEY,
        DNAME VARCHAR(64),
        LOC VARCHAR(64) );

INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH',   'DALLAS');
INSERT INTO DEPT VALUES (30, 'SALES',      'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');
select * from DEPT;


