micronaut:
  application:
    name: demo
datasources:
  default:
    url: ${JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: oracle.jdbc.driver.OracleDriver
    dialect: oracle
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
