apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
  - name: app
    image: ##DOCKER_PREFIX##/app
    ports:
    - containerPort: 8080
      name: app-port
    env:
    - name: JAVAX_SQL_DATASOURCE_DS1_DATASOURCE_URL
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: jdbc_url
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: db_user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: db_password
  imagePullSecrets:
  - name: ocirsecret        
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
  - name: http-service-port
    protocol: TCP
    port: 80
    targetPort: app-port
---